# Generated by Django 5.0.6 on 2024-05-28 17:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_alter_member_options_alter_member_table_comment"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="member",
            table_comment=None,
        ),
        migrations.AlterModelTable(
            name="member",
            table="Member",
        ),
    ]
